version: '3.8'

services:
  db:
    image: postgres:14
    restart: always
    env_file: .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  mlflow:
    build: .
    restart: always
    env_file: .env
    ports:
      - "5001:5000"
    depends_on:
      - db
    environment:
      - AWS_PROFILE=default
    volumes:
      - ~/.aws:/root/.aws:ro

volumes:
  pg_data:
